[build]
  publish = "."
  command = "npm install && node netlify/functions/generate-events.js"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 