[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Utiliser un script de build personnalisé pour générer les événements
[build.processing]
  skip_processing = false 