[build]
  command = "npm run build"
  publish = "./"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"

# Permettre l'exécution de fonctions après chaque déploiement
[build.processing]
  skip_processing = false

# Redirection pour l'interface admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Redirection pour les fonctions API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection pour la récupération des événements (ancienne méthode)
[[redirects]]
  from = "/get-events"
  to = "/.netlify/functions/get-events"
  status = 200
  force = true

# Redirection pour l'API des événements MongoDB
[[redirects]]
  from = "/api/events/*"
  to = "/.netlify/functions/get-events-mongodb"
  status = 200

# Redirection pour la création d'événements
[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/create-event"
  status = 200
  force = true
  methods = ["POST"]

# Redirection pour la mise à jour d'événements
[[redirects]]
  from = "/api/events/:id"
  to = "/.netlify/functions/update-event/:id"
  status = 200
  force = true
  methods = ["PUT"]

# Redirection pour la suppression d'événements
[[redirects]]
  from = "/api/events/:id"
  to = "/.netlify/functions/delete-event/:id"
  status = 200
  force = true
  methods = ["DELETE"]

# Headers pour autoriser les requêtes cross-origin
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Variables d'environnement pour le développement
[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 8888
  port = 8888
  publish = "."
  autoLaunch = true