[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/get-events"
  to = "/.netlify/functions/get-events"
  status = 200
  force = true

[[redirects]]
  from = "/get-partners"
  to = "/.netlify/functions/get-partners"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18.18.0"

# Permettre l'exécution de fonctions après chaque déploiement
[build.processing]
  skip_processing = false

# Configurer le plugin de génération des événements
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Ajouter des headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' https://cdn.auth0.com https://unpkg.com 'unsafe-inline'; style-src 'self' https://unpkg.com 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://api.github.com https://api.netlify.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"