[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Permettre l'exécution de fonctions après chaque déploiement
[build.processing]
  skip_processing = false

# Configurer le plugin de génération des événements
[[plugins]]
  package = "@netlify/plugin-functions-install-core"