# Configuration Netlify pour C.L.E.A.N.

[build]
  publish = "."
  command = "npm run build"
  functions = "api"

[dev]
  publish = "."
  functions = "api"
  port = 8888

# Redirection pour les fonctions API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection spécifique pour la récupération des événements
[[redirects]]
  from = "/api/get-events"
  to = "/.netlify/functions/get-events"
  status = 200

# Redirection spécifique pour l'API MongoDB
[[redirects]]
  from = "/api/mongodb-events"
  to = "/.netlify/functions/mongodb-events"
  status = 200

# Redirection pour la migration vers MongoDB
[[redirects]]
  from = "/api/migrate-to-mongodb"
  to = "/.netlify/functions/migrate-to-mongodb"
  status = 200

# Redirection pour la régénération des événements
[[redirects]]
  from = "/api/regenerate-events"
  to = "/.netlify/functions/regenerate-events"
  status = 200

# Variables d'environnement pour les fonctions serverless
[build.environment]
  NODE_VERSION = "16"

# Les variables sensibles (MONGODB_URI, JWT_SECRET) sont définies dans l'interface Netlify
# Ne pas les stocker dans ce fichier pour des raisons de sécurité

# Configuration pour les headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com; style-src 'self' https://unpkg.com 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://api.netlify.com;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Permettre l'exécution de fonctions après chaque déploiement
[build.processing]
  skip_processing = false

# Configurer le plugin de génération des événements
[[plugins]]
  package = "@netlify/plugin-functions-install-core"