name: Generate Events JSON

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths:
      - '_events/**'

# Définir les permissions nécessaires
permissions:
  contents: write

jobs:
  generate-events:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Utiliser le jeton GITHUB_TOKEN intégré
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install gray-matter
      
      - name: Generate events.json
        run: |
          # Script pour générer events.json à partir des fichiers Markdown
          node -e "
          const fs = require('fs');
          const path = require('path');
          const matter = require('gray-matter');
          
          // Lire tous les fichiers du dossier _events
          const eventsDir = path.join(process.cwd(), '_events');
          console.log('Dossier des événements:', eventsDir);
          
          if (!fs.existsSync(eventsDir)) {
            console.error('ERREUR: Le dossier _events n\'existe pas!');
            process.exit(1);
          }
          
          const files = fs.readdirSync(eventsDir);
          console.log('Fichiers trouvés:', files);
          
          if (files.length === 0) {
            console.warn('Aucun fichier trouvé dans le dossier _events');
          }
          
          // Traiter chaque fichier Markdown
          const events = files
            .filter(filename => filename.endsWith('.md'))
            .map(filename => {
              const filePath = path.join(eventsDir, filename);
              console.log('Traitement du fichier:', filePath);
              
              const fileContent = fs.readFileSync(filePath, 'utf8');
              const { data } = matter(fileContent);
              
              console.log('Données extraites:', JSON.stringify(data));
              
              return {
                title: data.title || 'Sans titre',
                date: data.date || 'À venir',
                description: data.description || '',
                image: data.image || null,
                link: data.link || '#contact',
                linkText: data.linkText || \"Plus d'informations\",
                order: data.order || 999
              };
            });
          
          console.log('Nombre d\'événements extraits:', events.length);
          
          // Trier les événements par ordre
          events.sort((a, b) => a.order - b.order);
          
          // Créer le répertoire api s'il n'existe pas
          const apiDir = path.join(process.cwd(), 'api');
          if (!fs.existsSync(apiDir)) {
            console.log('Création du dossier api');
            fs.mkdirSync(apiDir, { recursive: true });
          }
          
          // Écrire le fichier JSON
          const eventsJsonPath = path.join(apiDir, 'events.json');
          console.log('Écriture du fichier events.json à:', eventsJsonPath);
          
          fs.writeFileSync(
            eventsJsonPath,
            JSON.stringify(events, null, 2)
          );
          
          // Créer le fichier refresh.js avec un timestamp
          const timestamp = Date.now();
          const refreshPath = path.join(process.cwd(), 'refresh.js');
          console.log('Écriture du fichier refresh.js à:', refreshPath);
          
          fs.writeFileSync(
            refreshPath,
            \`// Timestamp: \${timestamp}
// Ce fichier est généré automatiquement pour forcer le rechargement des événements
console.log(\"Événements mis à jour le \${new Date().toLocaleString()}\");\`
          );
          
          console.log('Fichiers events.json et refresh.js générés avec succès');
          "
      
      # Utiliser une action dédiée pour pousser les modifications
      - name: Push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Mise à jour automatique des événements [skip ci]"
          file_pattern: "api/events.json refresh.js"
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_author: GitHub Action <action@github.com> 